//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyphenation.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyphenation.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % DEK&apos;s hyphenation exception list, from hyphen.tex; not changed.
        ///as-so-ciate
        ///as-so-ciates
        ///dec-li-na-tion
        ///oblig-a-tory
        ///phil-an-thropic
        ///present
        ///presents
        ///project
        ///projects
        ///re-cog-ni-zance
        ///ref-or-ma-tion
        ///ret-ri-bu-tion
        ///ta-ble
        ///acad-e-my
        ///acad-e-mies
        ///ac-cu-sa-tive
        ///acro-nym
        ///acro-nyms
        ///acu-punc-ture
        ///acu-punc-tur-ist
        ///ad-a-mant
        ///add-a-ble
        ///add-i-ble
        ///adren-a-line
        ///aero-space
        ///af-ter-thought
        ///af-ter-thoughts
        ///agron-o-mist
        ///agron-o-mists
        ///al-ge-bra-i-cal-ly
        ///al-ma-nac
        ///al-ma-nacs
        ///al-ma-nack
        ///al-ma-nacks
        ///anach-ro-nism
        ///anach-ro-nis-ti [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string hyph_en_us_hyp {
            get {
                return ResourceManager.GetString("hyph_en_us_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % begin hyphen.tex patterns:
        ///.ach4
        ///.ad4der
        ///.af1t
        ///.al3t
        ///.am5at
        ///.an5c
        ///.ang4
        ///.ani5m
        ///.ant4
        ///.an3te
        ///.anti5s
        ///.ar5s
        ///.ar4tie
        ///.ar4ty
        ///.as3c
        ///.as1p
        ///.as1s
        ///.aster5
        ///.atom5
        ///.au1d
        ///.av4i
        ///.awn4
        ///.ba4g
        ///.ba5na
        ///.bas4e
        ///.ber4
        ///.be5ra
        ///.be3sm
        ///.be5sto
        ///.bri2
        ///.but4ti
        ///.cam4pe
        ///.can5c
        ///.capa5b
        ///.car5ol
        ///.ca4t
        ///.ce4la
        ///.ch4
        ///.chill5i
        ///.ci2
        ///.cit5r
        ///.co3e
        ///.co4r
        ///.cor5ner
        ///.de4moi
        ///.de3o
        ///.de3ra
        ///.de3ri
        ///.des4c
        ///.dictio5
        ///.do4t
        ///.du4c
        ///.dumb5
        ///.earth5
        ///.eas3i
        ///.eb4
        ///.eer4
        ///.eg2
        ///.el5d
        ///.el3em
        ///.enam3
        ///.en3g
        ///.en3s
        ///.eq5ui5t
        ///.er4ri
        ///.es3
        ///.eu3
        ///.eye5
        ///.fes3
        ///.for5mer
        ///.ga2
        ///.ge2
        ///.g [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string hyph_en_us_pat {
            get {
                return ResourceManager.GetString("hyph_en_us_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % DEK&apos;s hyphenation exception list, from hyphen.tex; not changed.
        ///ас-бест
        ///бездн
        ///биз-нес-мен
        ///буй-нак-ске
        ///вбли-зи
        ///взба-ла-муть-ся
        ///вздрем-нешь
        ///во-до-сли-вом
        ///волж-ске
        ///воп-лем
        ///вопль
        ///вост-ра
        ///во-ткать
        ///во-ткем
        ///во-ткешь
        ///во-тку
        ///во-ткут
        ///впол-обо-ро-та
        ///впол-уха
        ///все-во-лож-ске
        ///вцспс
        ///га-рем-но-го
        ///го-ло-дра-нец
        ///грэс
        ///дву-зу-бец
        ///днепр
        ///добре-ем
        ///до-бре-ем-ся
        ///добре-ет
        ///добре-е-те
        ///до-бре-е-тесь
        ///до-бре-ет-ся
        ///добре-ешь
        ///до-бре-ешь-ся
        ///добрею
        ///до-бре-юсь
        ///добре-ют
        ///до-бре-ют-ся
        ///до-бре-сти
        ///до-бро-дят
        ///до-брось
        ///до-брось-те
        ///до-бро-сят
        ///до-бр [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string hyph_ru_hyp {
            get {
                return ResourceManager.GetString("hyph_ru_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % begin hyphen.tex patterns:
        ///.аб1р
        ///.аг1ро
        ///.ади2
        ///.аи2
        ///.ак1р
        ///.аль3я
        ///.ар2т1о2
        ///.ас1то
        ///.аст1р
        ///.ау2
        ///.би2о
        ///.во2б3л
        ///.во3ж2д
        ///.го2ф
        ///.дек2
        ///.де1кв
        ///.ди2ак
        ///.ди1о
        ///.до3п
        ///.до3т2
        ///.епи3
        ///.зав2р
        ///.за3м2н
        ///.за3п
        ///.иг1р
        ///.изг2
        ///.из3н
        ///.ии2
        ///.ик1р
        ///.ио2
        ///.ио4на
        ///.ис3
        ///.ле2о
        ///.ле2п3р
        ///.лес1к
        ///.ль2
        ///.люст1
        ///.ме2ж1у2
        ///.ми1ом
        ///.мо2к1
        ///.му2шт1
        ///.на1в
        ///.на3т
        ///.на3ш2
        ///.не3вн
        ///.не1др
        ///.не1з2
        ///.не1сл
        ///.не1с2ц
        ///.не3т
        ///.нос1к
        ///.нук1л
        ///.обо3ж2
        ///.ово1
        ///.ог3н
        ///.оз4
        ///.ос2ка
        ///.ос2п
        ///.ос3пи
        ///.от1в
        ///.от1ро
        ///.от1ру
        ///.от1уж
        ///.по3в2
        ///.по3ж2
        ///.поз2н
        ///.прос2
        ///.ра2с3т
        ///.ре2бр
        ///.ре2з3в
        ///.ри2ск
        ///.ри2ч
        ///.ро [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string hyph_ru_pat {
            get {
                return ResourceManager.GetString("hyph_ru_pat", resourceCulture);
            }
        }
    }
}
